export const ADMIN_LOGIN_LOCAL = 'ADMIN_LOGIN_LOCAL';
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS';


export const ADMIN_GET_PRODUCTS = 'ADMIN_GET_PRODUCTS';
export const ADMIN_GET_PRODUCTS_SUCCESS = 'ADMIN_GET_PRODUCTS_SUCCESS';
export const ADMIN_GET_PRODUCTS_FAILED = 'ADMIN_GET_PRODUCTS_FAILED';
export const ADMIN_ADD_PRODUCT = 'ADMIN_ADD_PRODUCT';
export const ADMIN_ADD_PRODUCT_SUCCESS = 'ADMIN_ADD_PRODUCT_SUCCESS';
export const ADMIN_ADD_PRODUCT_FAILED = 'ADMIN_ADD_PRODUCT_FAILED';
export const ADMIN_UPDATE_PRODUCT = 'ADMIN_UPDATE_PRODUCT';
export const ADMIN_UPDATE_PRODUCT_SUCCESS = 'ADMIN_UPDATE_PRODUCT_SUCCESS';
export const ADMIN_UPDATE_PRODUCT_FAILED = 'ADMIN_UPDATE_PRODUCT_FAILED';
export const ADMIN_DELETE_PRODUCT = 'ADMIN_DELETE_PRODUCT';
export const ADMIN_DELETE_PRODUCT_SUCCESS = 'ADMIN_DELETE_PRODUCT_SUCCESS';
export const ADMIN_DELETE_PRODUCT_FAILED = 'ADMIN_DELETE_PRODUCT_FAILED';
export const ADMIN_DELETE_MULTI_PRODUCT = 'ADMIN_DELETE_MULTI_PRODUCT';
export const ADMIN_DELETE_MULTI_PRODUCT_SUCCESS = 'ADMIN_DELETE_MULTI_PRODUCT_SUCCESS';
export const ADMIN_DELETE_MULTI_PRODUCT_FAILED = 'ADMIN_DELETE_MULTI_PRODUCT_FAILED';


export const ADMIN_GET_FRONTS = 'ADMIN_GET_FRONTS';
export const ADMIN_GET_FRONTS_SUCCESS = 'ADMIN_GET_FRONTS_SUCCESS';
export const ADMIN_GET_FRONTS_FAILED = 'ADMIN_GET_FRONTS_FAILED';

export const ADMIN_GET_SIZES = 'ADMIN_GET_SIZES';
export const ADMIN_GET_SIZES_SUCCESS = 'ADMIN_GET_SIZES_SUCCESS';
export const ADMIN_GET_SIZES_FAILED = 'ADMIN_GET_SIZES_FAILED';
export const ADMIN_ADD_SIZE = 'ADMIN_ADD_SIZE';
export const ADMIN_ADD_SIZE_SUCCESS = 'ADMIN_ADD_SIZE_SUCCESS';
export const ADMIN_ADD_SIZE_FAILED = 'ADMIN_ADD_SIZE_FAILED';
export const ADMIN_UPDATE_SIZE = 'ADMIN_UPDATE_SIZE';
export const ADMIN_UPDATE_SIZE_SUCCESS = 'ADMIN_UPDATE_SIZE_SUCCESS';
export const ADMIN_UPDATE_SIZE_FAILED = 'ADMIN_UPDATE_SIZE_FAILED';
export const ADMIN_DELETE_SIZE = 'ADMIN_DELETE_SIZE';
export const ADMIN_DELETE_SIZE_SUCCESS = 'ADMIN_DELETE_SIZE_SUCCESS';
export const ADMIN_DELETE_SIZE_FAILED = 'ADMIN_DELETE_SIZE_FAILED';
export const ADMIN_DELETE_MULTI_SIZE = 'ADMIN_DELETE_MULTI_SIZE';
export const ADMIN_DELETE_MULTI_SIZE_SUCCESS = 'ADMIN_DELETE_MULTI_SIZE_SUCCESS';
export const ADMIN_DELETE_MULTI_SIZE_FAILED = 'ADMIN_DELETE_MULTI_SIZE_FAILED';

export const ADMIN_GET_ROOMS = 'ADMIN_GET_ROOMS';
export const ADMIN_GET_ROOMS_SUCCESS = 'ADMIN_GET_ROOMS_SUCCESS';
export const ADMIN_GET_ROOMS_FAILED = 'ADMIN_GET_ROOMS_FAILED';

export const ADMIN_GET_LAYOUTS = 'ADMIN_GET_LAYOUTS';
export const ADMIN_GET_LAYOUTS_SUCCESS = 'ADMIN_GET_LAYOUTS_SUCCESS';
export const ADMIN_GET_LAYOUTS_FAILED = 'ADMIN_GET_LAYOUTS_FAILED';
export const ADMIN_ADD_LAYOUT = 'ADMIN_ADD_LAYOUT';
export const ADMIN_ADD_LAYOUT_SUCCESS = 'ADMIN_ADD_LAYOUT_SUCCESS';
export const ADMIN_ADD_LAYOUT_FAILED = 'ADMIN_ADD_LAYOUT_FAILED';
export const ADMIN_CLONE_LAYOUT = 'ADMIN_CLONE_LAYOUT';
export const ADMIN_CLONE_LAYOUT_SUCCESS = 'ADMIN_CLONE_LAYOUT_SUCCESS';
export const ADMIN_CLONE_LAYOUT_FAILED = 'ADMIN_CLONE_LAYOUT_FAILED';
export const ADMIN_UPDATE_LAYOUT = 'ADMIN_UPDATE_LAYOUT';
export const ADMIN_UPDATE_LAYOUT_SUCCESS = 'ADMIN_UPDATE_LAYOUT_SUCCESS';
export const ADMIN_UPDATE_LAYOUT_FAILED = 'ADMIN_UPDATE_LAYOUT_FAILED';
export const ADMIN_DELETE_LAYOUT = 'ADMIN_DELETE_LAYOUT';
export const ADMIN_DELETE_LAYOUT_SUCCESS = 'ADMIN_DELETE_LAYOUT_SUCCESS';
export const ADMIN_DELETE_LAYOUT_FAILED = 'ADMIN_DELETE_LAYOUT_FAILED';
export const ADMIN_DELETE_MULTI_LAYOUT = 'ADMIN_DELETE_MULTI_LAYOUT';
export const ADMIN_DELETE_MULTI_LAYOUT_SUCCESS = 'ADMIN_DELETE_MULTI_LAYOUT_SUCCESS';
export const ADMIN_DELETE_MULTI_LAYOUT_FAILED = 'ADMIN_DELETE_MULTI_LAYOUT_FAILED';


export const ADMIN_GET_SETTING = 'ADMIN_GET_SETTING';
export const ADMIN_GET_SETTING_SUCCESS = 'ADMIN_GET_SETTING_SUCCESS';
export const ADMIN_GET_SETTING_FAILED = 'ADMIN_GET_SETTING_FAILED';
export const ADMIN_UPDATE_SETTING = 'ADMIN_UPDATE_SETTING';
export const ADMIN_UPDATE_SETTING_SUCCESS = 'ADMIN_UPDATE_SETTING_SUCCESS';
export const ADMIN_UPDATE_SETTING_FAILED = 'ADMIN_UPDATE_SETTING_FAILED';