export const ADMIN_LOGIN_LOCAL = 'ADMIN_LOGIN_LOCAL';
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS';


export const ADMIN_GET_EXHIBITOR = 'ADMIN_GET_EXHIBITOR';
export const ADMIN_GET_EXHIBITOR_SUCCESS = 'ADMIN_GET_EXHIBITOR_SUCCESS';
export const ADMIN_GET_EXHIBITOR_FAILED = 'ADMIN_GET_EXHIBITOR_FAILED';

export const ADMIN_GET_VISITOR = 'ADMIN_GET_VISITOR';
export const ADMIN_GET_VISITOR_SUCCESS = 'ADMIN_GET_VISITOR_SUCCESS';
export const ADMIN_GET_VISITOR_FAILED = 'ADMIN_GET_VISITOR_FAILED';

export const ADMIN_ADD_USER = 'ADMIN_ADD_USER';
export const ADMIN_ADD_USER_SUCCESS = 'ADMIN_ADD_USER_SUCCESS';
export const ADMIN_ADD_USER_FAILED = 'ADMIN_ADD_USER_FAILED';

export const ADMIN_UPDATE_USER = 'ADMIN_UPDATE_USER';
export const ADMIN_UPDATE_USER_SUCCESS = 'ADMIN_UPDATE_USER_SUCCESS';
export const ADMIN_UPDATE_USER_FAILED = 'ADMIN_UPDATE_USER_FAILED';
export const ADMIN_DELETE_USER = 'ADMIN_DELETE_USER';
export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS';
export const ADMIN_DELETE_USER_FAILED = 'ADMIN_DELETE_USER_FAILED';
export const ADMIN_DELETE_MULTI_USER = 'ADMIN_DELETE_MULTI_USER';
export const ADMIN_DELETE_MULTI_USER_SUCCESS = 'ADMIN_DELETE_MULTI_USER_SUCCESS';
export const ADMIN_DELETE_MULTI_USER_FAILED = 'ADMIN_DELETE_MULTI_USER_FAILED';


export const SET_TOOLTIP = 'SET_TOOLTIP';

export const ADMIN_GET_INDUSTRIES = 'ADMIN_GET_INDUSTRIES';
export const ADMIN_GET_INDUSTRIES_SUCCESS = 'ADMIN_GET_INDUSTRIES_SUCCESS';
export const ADMIN_GET_INDUSTRIES_FAILED = 'ADMIN_GET_INDUSTRIES_FAILED';
export const ADMIN_ADD_INDUSTRY = 'ADMIN_ADD_INDUSTRY';
export const ADMIN_ADD_INDUSTRY_SUCCESS = 'ADMIN_ADD_INDUSTRY_SUCCESS';
export const ADMIN_ADD_INDUSTRY_FAILED = 'ADMIN_ADD_INDUSTRY_FAILED';
export const ADMIN_UPDATE_INDUSTRY = 'ADMIN_UPDATE_INDUSTRY';
export const ADMIN_UPDATE_INDUSTRY_SUCCESS = 'ADMIN_UPDATE_INDUSTRY_SUCCESS';
export const ADMIN_UPDATE_INDUSTRY_FAILED = 'ADMIN_UPDATE_INDUSTRY_FAILED';
export const ADMIN_DELETE_INDUSTRY = 'ADMIN_DELETE_INDUSTRY';
export const ADMIN_DELETE_INDUSTRY_SUCCESS = 'ADMIN_DELETE_INDUSTRY_SUCCESS';
export const ADMIN_DELETE_INDUSTRY_FAILED = 'ADMIN_DELETE_INDUSTRY_FAILED';
export const ADMIN_DELETE_MULTI_INDUSTRY = 'ADMIN_DELETE_MULTI_INDUSTRY';
export const ADMIN_DELETE_MULTI_INDUSTRY_SUCCESS = 'ADMIN_DELETE_MULTI_INDUSTRY_SUCCESS';
export const ADMIN_DELETE_MULTI_INDUSTRY_FAILED = 'ADMIN_DELETE_MULTI_INDUSTRY_FAILED';


export const ADMIN_GET_USER = 'ADMIN_GET_USER';
export const ADMIN_GET_USER_SUCCESS = 'ADMIN_GET_USER_SUCCESS';
export const ADMIN_GET_USER_FAILED = 'ADMIN_GET_USER_FAILED';

export const ADMIN_EXHIBITOR_LOGOUT = 'ADMIN_EXHIBITOR_LOGOUT';


export const ADMIN_ADD_CATEGORY = 'ADMIN_ADD_CATEGORY';
export const ADMIN_ADD_CATEGORY_SUCCESS = 'ADMIN_ADD_CATEGORY_SUCCESS';
export const ADMIN_ADD_CATEGORY_FAILED = 'ADMIN_ADD_CATEGORY_FAILED';
export const ADMIN_GET_CATEGORIES = 'ADMIN_GET_CATEGORIES';
export const ADMIN_GET_CATEGORIES_SUCCESS = 'ADMIN_GET_CATEGORIES_SUCCESS';
export const ADMIN_GET_CATEGORIES_FAILED = 'ADMIN_GET_CATEGORIES_FAILED';
export const ADMIN_UPDATE_CATEGORY = 'ADMIN_UPDATE_CATEGORY';
export const ADMIN_UPDATE_CATEGORY_SUCCESS = 'ADMIN_UPDATE_CATEGORY_SUCCESS';
export const ADMIN_UPDATE_CATEGORY_FAILED = 'ADMIN_UPDATE_CATEGORY_FAILED';
export const ADMIN_DELETE_CATEGORY = 'ADMIN_DELETE_CATEGORY';
export const ADMIN_DELETE_CATEGORY_SUCCESS = 'ADMIN_DELETE_CATEGORY_SUCCESS';
export const ADMIN_DELETE_CATEGORY_FAILED = 'ADMIN_DELETE_CATEGORY_FAILED';
export const ADMIN_DELETE_MULTI_CATEGORY = 'ADMIN_DELETE_MULTI_CATEGORY';
export const ADMIN_DELETE_MULTI_CATEGORY_SUCCESS = 'ADMIN_DELETE_MULTI_CATEGORY_SUCCESS';
export const ADMIN_DELETE_MULTI_CATEGORY_FAILED = 'ADMIN_DELETE_MULTI_CATEGORY_FAILED';

export const ADMIN_GET_PRODUCTS = 'ADMIN_GET_PRODUCTS';
export const ADMIN_GET_PRODUCTS_SUCCESS = 'ADMIN_GET_PRODUCTS_SUCCESS';
export const ADMIN_GET_PRODUCTS_FAILED = 'ADMIN_GET_PRODUCTS_FAILED';
export const ADMIN_ADD_PRODUCT = 'ADMIN_ADD_PRODUCT';
export const ADMIN_ADD_PRODUCT_SUCCESS = 'ADMIN_ADD_PRODUCT_SUCCESS';
export const ADMIN_ADD_PRODUCT_FAILED = 'ADMIN_ADD_PRODUCT_FAILED';
export const ADMIN_UPDATE_PRODUCT = 'ADMIN_UPDATE_PRODUCT';
export const ADMIN_UPDATE_PRODUCT_SUCCESS = 'ADMIN_UPDATE_PRODUCT_SUCCESS';
export const ADMIN_UPDATE_PRODUCT_FAILED = 'ADMIN_UPDATE_PRODUCT_FAILED';
export const ADMIN_DELETE_PRODUCT = 'ADMIN_DELETE_PRODUCT';
export const ADMIN_DELETE_PRODUCT_SUCCESS = 'ADMIN_DELETE_PRODUCT_SUCCESS';
export const ADMIN_DELETE_PRODUCT_FAILED = 'ADMIN_DELETE_PRODUCT_FAILED';
export const ADMIN_DELETE_MULTI_PRODUCT = 'ADMIN_DELETE_MULTI_PRODUCT';
export const ADMIN_DELETE_MULTI_PRODUCT_SUCCESS = 'ADMIN_DELETE_MULTI_PRODUCT_SUCCESS';
export const ADMIN_DELETE_MULTI_PRODUCT_FAILED = 'ADMIN_DELETE_MULTI_PRODUCT_FAILED';
