export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const GET_FRONTS = 'GET_FRONTS';
export const GET_FRONTS_SUCCESS = 'GET_FRONTS_SUCCESS';
export const GET_FRONTS_FAILED = 'GET_FRONTS_FAILED';
export const FRONTS_SELECT_ALL = 'FRONTS_SELECT_ALL';
export const FRONTS_CLEAR_ALL = 'FRONTS_CLEAR_ALL';
export const FRONTS_SELECT_ONE = 'FRONTS_SELECT_ONE';
export const FRONTS_REVERSE = 'FRONTS_REVERSE';

export const GET_SIZES = 'GET_SIZES';
export const GET_SIZES_SUCCESS = 'GET_SIZES_SUCCESS';
export const GET_SIZES_FAILED = 'GET_SIZES_FAILED';
export const SIZES_SELECT_ALL = 'SIZES_SELECT_ALL';
export const SIZES_CLEAR_ALL = 'SIZES_CLEAR_ALL';
export const SIZES_SELECT_ONE = 'SIZES_SELECT_ONE';
export const SIZES_REVERSE = 'SIZES_REVERSE';

export const GET_ROOMS = 'GET_ROOMS';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAILED = 'GET_ROOMS_FAILED';

export const GET_LAYOUTS = 'GET_LAYOUTS';
export const GET_LAYOUTS_SUCCESS = 'GET_LAYOUTS_SUCCESS';
export const GET_LAYOUTS_FAILED = 'GET_LAYOUTS_FAILED';

export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const LOCATIONS_SELECT_ALL = 'LOCATIONS_SELECT_ALL';
export const LOCATIONS_CLEAR_ALL = 'LOCATIONS_CLEAR_ALL';
export const LOCATIONS_SELECT_ONE = 'LOCATIONS_SELECT_ONE';
export const LOCATIONS_REVERSE = 'LOCATIONS_REVERSE';


export const CHANGE_SEARCH = 'CHANGE_SEARCH';


export const HIDE_TOPPANEL = 'HIDE_TOPPANEL';

export const CHANGE_GROUT = 'CHANGE_GROUT';
export const CHANGE_COLOR = 'CHANGE_COLOR';
export const CHANGE_CUSTOM = 'CHANGE_CUSTOM';
export const CHANGE_CUSTOM_ROTATE = 'CHANGE_CUSTOM_ROTATE';

export const SELECT_LAYOUT = 'SELECT_LAYOUT';
export const SELECT_AREA = 'SELECT_AREA';

export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECT_FIRST_PRODUCT = 'SELECT_FIRST_PRODUCT';
export const SELECT_SECOND_PRODUCT = 'SELECT_SECOND_PRODUCT';

export const CHANGE_SKEW_TYPE = 'CHANGE_SKEW_TYPE';
export const CHANGE_SKEW_VALUE = 'CHANGE_SKEW_VALUE';

export const CHANGE_ROTATE = 'CHANGE_ROTATE';

export const CHANGE_SORT = 'CHANGE_SORT';

export const PROGRESS_UPDATE = 'PROGRESS_UPDATE';

//error
export const NO_TITLE_SELECTED = 'NO_TITLE_SELECTED';