export const GET_INDUSTRIES = 'GET_INDUSTRIES';
export const GET_INDUSTRIES_SUCCESS = 'GET_INDUSTRIES_SUCCESS';
export const GET_INDUSTRIES_FAILED = 'GET_INDUSTRIES_FAILED';

export const GET_EXHIBITORS = 'GET_EXHIBITORS';
export const GET_EXHIBITORS_SUCCESS = 'GET_EXHIBITORS_SUCCESS';
export const GET_EXHIBITORS_FAILED = 'GET_EXHIBITORS_FAILED';

export const GET_VISITORS = 'GET_VISITORS';
export const GET_VISITORS_SUCCESS = 'GET_VISITORS_SUCCESS';
export const GET_VISITORS_FAILED = 'GET_VISITORS_FAILED';


export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_LOCAL = 'USER_LOGIN_LOCAL';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';


export const OPENFORM = 'OPENFORM';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATIONS_FAILED = 'GET_CONVERSATIONS_FAILED';

export const GET_ONE_CONVERSATION = 'GET_ONE_CONVERSATION';
export const GET_ONE_CONVERSATION_SUCCESS = 'GET_ONE_CONVERSATION_SUCCESS';
export const GET_ONE_CONVERSATION_FAILED = 'GET_ONE_CONVERSATION_FAILED';

export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILED = 'GET_MESSAGES_FAILED';

export const READ_CONVERSATION = 'READ_CONVERSATION';
export const READ_CONVERSATION_SUCCESS = 'READ_CONVERSATION_SUCCESS';
export const READ_CONVERSATION_FAILED = 'READ_CONVERSATION_FAILED';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';

export const OPEN_MESSAGE = 'OPEN_MESSAGE';
export const OPEN_LIST = 'OPEN_LIST';

export const SELECT_CONVERSATION = 'SELECT_CONVERSATION';
export const SELECT_CONVERSATION_SUCCESS = 'SELECT_CONVERSATION_SUCCESS';
export const SELECT_CONVERSATION_FAILED = 'SELECT_CONVERSATION_FAILED';