export const GET_INDUSTRIES = 'GET_INDUSTRIES';
export const GET_INDUSTRIES_SUCCESS = 'GET_INDUSTRIES_SUCCESS';
export const GET_INDUSTRIES_FAILED = 'GET_INDUSTRIES_FAILED';

export const GET_EXHIBITORS = 'GET_EXHIBITORS';
export const GET_EXHIBITORS_SUCCESS = 'GET_EXHIBITORS_SUCCESS';
export const GET_EXHIBITORS_FAILED = 'GET_EXHIBITORS_FAILED';

export const GET_VISITORS = 'GET_VISITORS';
export const GET_VISITORS_SUCCESS = 'GET_VISITORS_SUCCESS';
export const GET_VISITORS_FAILED = 'GET_VISITORS_FAILED';


export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_LOCAL = 'USER_LOGIN_LOCAL';
export const USER_LOGIN_FACEBOOK = 'USER_LOGIN_FACEBOOK';
export const USER_LOGIN_GOOGLE = 'USER_LOGIN_GOOGLE';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';



export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';


export const OPENFORM = 'OPENFORM';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATIONS_FAILED = 'GET_CONVERSATIONS_FAILED';

export const GET_ONE_CONVERSATION = 'GET_ONE_CONVERSATION';
export const GET_ONE_CONVERSATION_SUCCESS = 'GET_ONE_CONVERSATION_SUCCESS';
export const GET_ONE_CONVERSATION_FAILED = 'GET_ONE_CONVERSATION_FAILED';

export const GET_CONVERSATION_TO = 'GET_CONVERSATION_TO';
export const GET_CONVERSATION_TO_SUCCESS = 'GET_CONVERSATION_TO_SUCCESS';
export const GET_CONVERSATION_TO_FAILED = 'GET_CONVERSATION_TO_FAILED';

export const SELECT_CONVERSATION = 'SELECT_CONVERSATION';
export const SELECT_CONVERSATION_SUCCESS = 'SELECT_CONVERSATION_SUCCESS';
export const SELECT_CONVERSATION_FAILED = 'SELECT_CONVERSATION_FAILED';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';

export const READ_MESSAGE = 'READ_MESSAGE';
export const READ_MESSAGE_SUCCESS = 'READ_MESSAGE_SUCCESS';
export const READ_MESSAGE_FAILED = 'READ_MESSAGE_FAILED';

export const REVICED_MESSAGE = 'REVICED_MESSAGE';
export const REVICED_MESSAGE_SUCCESS = 'REVICED_MESSAGE_SUCCESS';
export const REVICED_MESSAGE_FAILED = 'REVICED_MESSAGE_FAILED';

export const OPEN_MESSAGE = 'OPEN_MESSAGE';
export const OPEN_LIST = 'OPEN_LIST';


export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

export const SEND_CONTACT = 'SEND_CONTACT';
export const SEND_CONTACT_SUCCESS = 'SEND_CONTACT_SUCCESS';
export const SEND_CONTACT_FAILED = 'SEND_CONTACT_FAILED';

export const GET_SETTING = 'GET_SETTING';
export const GET_SETTING_SUCCESS = 'GET_SETTING_SUCCESS';
export const GET_SETTING_FAILED = 'GET_SETTING_FAILED';


export const GET_ADMIN_INFO = 'GET_ADMIN_INFO';
export const GET_ADMIN_INFO_SUCCESS = 'GET_ADMIN_INFO_SUCCESS';
export const GET_ADMIN_INFO_FAILED = 'GET_ADMIN_INFO_FAILED';

export const ADD_TRADE = 'ADD_TRADE';
export const ADD_TRADE_SUCCESS = 'ADD_TRADE_SUCCESS';
export const ADD_TRADE_FAILED = 'ADD_TRADE_FAILED';
export const GET_TRADES = 'GET_TRADES';
export const GET_TRADES_SUCCESS = 'GET_TRADES_SUCCESS';
export const GET_TRADES_FAILED = 'GET_TRADES_FAILED';
export const UPDATE_TRADE = 'UPDATE_TRADE';
export const UPDATE_TRADE_SUCCESS = 'UPDATE_TRADE_SUCCESS';
export const UPDATE_TRADE_FAILED = 'UPDATE_TRADE_FAILED';
export const DELETE_TRADE = 'DELETE_TRADE';
export const DELETE_TRADE_SUCCESS = 'DELETE_TRADE_SUCCESS';
export const DELETE_TRADE_FAILED = 'DELETE_TRADE_FAILED';
export const DELETE_MULTI_TRADE = 'DELETE_MULTI_TRADE';
export const DELETE_MULTI_TRADE_SUCCESS = 'DELETE_MULTI_TRADE_SUCCESS';
export const DELETE_MULTI_TRADE_FAILED = 'DELETE_MULTI_TRADE_FAILED';

export const CREATE_TRADE = 'CREATE_TRADE';

export const GET_LIVESTREAM = 'GET_LIVESTREAM';
export const GET_LIVESTREAM_SUCCESS = 'GET_LIVESTREAM_SUCCESS';
export const GET_LIVESTREAM_FAILED = 'GET_LIVESTREAM_FAILED';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';


export const VERIFY_ACCOUNT = 'VERIFY_ACCOUNT';
export const VERIFY_ACCOUNT_SUCCESS = 'VERIFY_ACCOUNT_SUCCESS';
export const VERIFY_ACCOUNT_FAILED = 'VERIFY_ACCOUNT_FAILED';


export const GET_VISIT = 'GET_VISIT';
export const GET_VISIT_SUCCESS = 'GET_VISIT_SUCCESS';
export const GET_VISIT_FAILED = 'GET_VISIT_FAILED';