export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_LOCAL = 'USER_LOGIN_LOCAL';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';

export const USER_ADD_DESIGN = 'USER_ADD_DESIGN';
export const USER_ADD_DESIGN_SUCCESS = 'USER_ADD_DESIGN_SUCCESS';
export const USER_ADD_DESIGN_FAILED = 'USER_ADD_DESIGN_FAILED';

export const USER_UPDATE_DESIGN = 'USER_UPDATE_DESIGN';
export const USER_UPDATE_DESIGN_SUCCESS = 'USER_UPDATE_DESIGN_SUCCESS';
export const USER_UPDATE_DESIGN_FAILED = 'USER_UPDATE_DESIGN_FAILED';

export const USER_DELETE_DESIGN = 'USER_DELETE_DESIGN';
export const USER_DELETE_DESIGN_SUCCESS = 'USER_DELETE_DESIGN_SUCCESS';
export const USER_DELETE_DESIGN_FAILED = 'USER_DELETE_DESIGN_FAILED';

export const USER_DELETE_MUTIL_DESIGN = 'USER_DELETE_MUTIL_DESIGN';
export const USER_DELETE_MUTIL_DESIGN_SUCCESS = 'USER_DELETE_MUTIL_DESIGN_SUCCESS';
export const USER_DELETE_MUTIL_DESIGN_FAILED = 'USER_DELETE_MUTIL_DESIGN_FAILED';

export const USER_GET_DESIGN = 'USER_GET_DESIGN';
export const USER_GET_DESIGN_SUCCESS = 'USER_GET_DESIGN_SUCCESS';
export const USER_GET_DESIGN_FAILED = 'USER_GET_DESIGN_FAILED';

export const USER_GET_MY_DESIGN = 'USER_GET_MY_DESIGN';
export const USER_GET_MY_DESIGN_SUCCESS = 'USER_GET_MY_DESIGN_SUCCESS';
export const USER_GET_MY_DESIGN_FAILED = 'USER_GET_MY_DESIGN_FAILED';
